# ================================ #
#             override             #
# ================================ #
# specify default configuration; the order determines the override order
defaults:
  - _self_
  # pytorch-lightning
  - data: ???
  - model: ???
  - callbacks: null

  # system
  - hydra: default

  # utility groups that changes a lot
  - pipeline: null
  - network: null
  - optimizer: null
  - scheduler_cfg: default
  - train_datasets: null
  - test_datasets: null
  - endecoder: null # normalize/unnormalize data
  - refiner: null

  # global-override
  - exp: ??? # set "data, model and callbacks" in yaml
  - global/task: null # dump/test
  - global/hsearch: null # hyper-param search
  - global/debug: null # debug mode

# ================================ #
#          global setting          #
# ================================ #
# expirement information
task: fit # [fit, predict]
exp_name: ???
data_name: ???

# utilities in the entry file
output_dir: "outputs/${data_name}/${exp_name}"
ckpt_path: null
resume_mode: null
seed: 42

# lightning default settings
pl_trainer:
  devices: 1
  num_sanity_val_steps: 0 # disable sanity check
  precision: 32
  inference_mode: False

logger: null
