# @package _global_
defaults:
  - override /data: mocap/testY
  - override /test_datasets:
      - rich/all
      - emdb1/v1_fliptest
      - emdb2/v1_fliptest
      - 3dpw/fliptest
  - override /callbacks:
      - metric_rich
      - metric_emdb1
      - metric_emdb2
      - metric_3dpw
  - _self_

task: test
data_name: test_mocap
ckpt_path: ??? # will not override previous setting if already set

# lightning utilities
pl_trainer:
  devices: 1
logger: null
